---
- name: Change port
  hosts: web2
  gather_facts: no
  tasks:
    - name: Ping
      ping:
      
    - name: change etc/ssh/sshd_config
      lineinfile:
        path: "etc/ssh/sshd_config"
        regexp: '^Port 2222'
        line: 'Port 7789'

    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted